In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
text = ['This is a line',
        'This is another line',
        'Completely different line'
       ]

In [22]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [25]:
cv = CountVectorizer()

In [26]:
sparse_matrix = cv.fit_transform(text)

In [27]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [28]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [29]:
tfidf = TfidfTransformer()

In [30]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [31]:
results = tfidf.fit_transform(sparse_matrix)

In [33]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tv = TfidfVectorizer()

In [36]:
tv_result=tv.fit_transform(text)

In [38]:
tv_result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])