# Feature Scaling
Feature scaling provides many benifits to our machine learning process

1. Some machine learning models that rely on distance metrics require scaling to perform well.
2. Benifits of feature scaling
    1. Feature scaling improves the convergence of steepest descent algorithm which do not possess the property of scale invarience.
    2. If features are on differente scales, certain weights may update faster than others since the feature values x(j) play a role in weight updates.
    3. Critical benifits of feature scaling related to gradient descent.
    4. There are some ML algos where scaling won't have an effect.

Two main ways to scale features:
1. Standaradization
    1. Rescales data to have a mean(mue) of 0 and standard deviation(sigma) of 1.
2. Normalization
    1. Rescales all data values to be between 0-1.

# Standardization
1. Rescale data to have a mean(mue) of 0 and standard deviation(sigma) of 1(unit variance).
        X(changed) =(X - mue) / sigma.
2. Nmaesake can be confusung since this is also reffered to as "Z-score normalization".

# Normalization
1. Scale all data values to be between 0 and 1.
        X(changed) = (X-X(min))/(X(max)-X(min)).
2. It is simple and esay to understand.


There are amny more methods of scaling features and Scikit Learn provides easy to use classes that "fit" and "transform" feature data for scaling.

1. A .fir() method call simply calculates the necessary statistics(Xmin, Xmax, mean, standard deviation).
2. A .transform() call actually scalles data and returns the new scaled version of data. 


1. we only fit to training data.
2. Calculating statistical information should only come from traning data.
3. Don't want to assume prior knowledge of the test set.

Using the full data set would cause data leakage:
1. Claculating statistics from full data leads to some information of the test set leaking into the training process upon transform() conversion.

# Feature Scaling process:
1. Perform train test split
2. Fit to training feature data.
3. Transform training feature data.
4. Transform test feature data.

# Do we need to scale the label?
1. In general it is not necessary nor advice.
2. Normalising the output distribution is altering the defination of the target.
3. Predicting a distribution that doesn't mirror your real-world-target.
4. Can negatively impact stochastic gradient descent.

# Cross validation

It is a more advanced set of methods for splitting data into training and testing sets.

# Regularization for Linear Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
X= df.drop('sales', axis =1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
poly_convertor  = PolynomialFeatures(degree=3, include_bias=False)

In [7]:
poly_features = poly_convertor.fit_transform(X)

In [8]:
poly_features.shape

(200, 19)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [11]:
X_train.shape

(140, 19)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train = scaler.transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [18]:
# poly_features[0]

# Ridge Regression

1. It is a regularization technique that works by helping reduce the potential for overfitting to the training data.
2. It does this by adding in a penatly term to the error that is based on the squred value of the coefficents.
3. Ridge regression is a regularization method for Linear Regression.

In [19]:
from sklearn.linear_model import Ridge

In [20]:
ridg_model = Ridge(alpha=10)

In [21]:
ridg_model.fit(X_train, y_train)

Ridge(alpha=10)

In [22]:
test_pred = ridg_model.predict(X_test)

In [23]:
test_pred

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [25]:
MAE = mean_absolute_error(y_test, test_pred)

In [26]:
MAE

0.5774404204714183

In [27]:
RMSE = np.sqrt(mean_squared_error(y_test, test_pred))

In [28]:
RMSE

0.8946386461319685

In [30]:
from sklearn.linear_model import RidgeCV

In [38]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring= 'neg_mean_absolute_error')

In [39]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [40]:
#  which alpha perameter perform best
ridge_cv_model.alpha_

0.1

In [43]:
# from sklearn.metrics import SCORERS

In [44]:
# SCORERS.keys()

In [45]:
test_pred = ridge_cv_model.predict(X_test)

In [46]:
MAE = mean_absolute_error(y_test, test_pred)

In [47]:
MAE

0.42737748843352086

In [48]:
RMSE = np.sqrt(mean_squared_error(y_test, test_pred))

In [50]:
# RMSE = Root Mean Squared Error
RMSE

0.6180719926924644

In [51]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

# Lasso Regression (L1)

L1 regularization adds a penalty equal to the absolute value of the magnitude of coefficients.

In [52]:
from sklearn.linear_model import LassoCV

In [70]:
lasso_cv_model = LassoCV(eps = 0.001, n_alphas = 100, cv = 5, max_iter=1000000)
# lasso_cv_model = LassoCV(eps = 0.1, n_alphas = 100, cv = 5)

In [71]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, max_iter=1000000)

In [72]:
lasso_cv_model.alpha_

0.004943070909225827

In [73]:
test_pred = lasso_cv_model.predict(X_test)

In [74]:
MAE = mean_absolute_error(y_test, test_pred)

In [75]:
RMSE = np.sqrt(mean_squared_error(y_test, test_pred))

In [76]:
MAE

0.43350346185900673

In [77]:
RMSE

0.6063140748984039

In [78]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

# Elastic Net

We know Lasso is able to shrink coefficients to zero, but we have not  taken a deeper dive  into how or why that is. This ability becomes more clear when learning about elastic net which combines Lasso and Ridge together.

In [79]:
from sklearn.linear_model import ElasticNetCV

In [80]:
model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps = 0.001, n_alphas=100, max_iter=10000000)

In [81]:
model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=10000000)

In [82]:
model.l1_ratio_

1.0

In [83]:
model.alpha_

0.004943070909225827

In [84]:
test_pred = model.predict(X_test)

In [85]:
MAE = mean_absolute_error(y_test, test_pred)

In [89]:
RMSE = np.sqrt(mean_squared_error(y_test, test_pred))

In [90]:
MAE

0.43350346185900673

In [91]:
RMSE

0.6063140748984039

# Linear Regression Project 

Most data sets require cleaning, analysis, and feature engineering before being used for machine learning.

In [92]:
import pandas as pd

In [95]:
df = pd.read_csv('Ames_Housing_Data.csv')

In [97]:
df.head()

PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
0  526301100           20        RL         141.0     31770   Pave   NaN   
1  526350040           20        RH          80.0     11622   Pave   NaN   
2  526351010           20        RL          81.0     14267   Pave   NaN   
3  526353030           20        RL          93.0     11160   Pave   NaN   
4  527105010           60        RL          74.0     13830   Pave   NaN   

  Lot Shape Land Contour Utilities  ... Pool Area Pool QC  Fence Misc Feature  \
0       IR1          Lvl    AllPub  ...         0     NaN    NaN          NaN   
1       Reg          Lvl    AllPub  ...         0     NaN  MnPrv          NaN   
2       IR1          Lvl    AllPub  ...         0     NaN    NaN         Gar2   
3       Reg          Lvl    AllPub  ...         0     NaN    NaN          NaN   
4       IR1          Lvl    AllPub  ...         0     NaN  MnPrv          NaN   

  Misc Val Mo Sold Yr Sold  Sale Type  Sale Condition  SalePrice  
0        0       5    2010        WD           Normal     215000  
1        0       6    2010        WD           Normal     105000  
2    12500       6    2010        WD           Normal     172000  
3        0       4    2010        WD           Normal     244000  
4        0       3    2010        WD           Normal     189900  

[5 rows x 81 columns]

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   PID              2930 non-null   int64  
 1   MS SubClass      2930 non-null   int64  
 2   MS Zoning        2930 non-null   object 
 3   Lot Frontage     2440 non-null   float64
 4   Lot Area         2930 non-null   int64  
 5   Street           2930 non-null   object 
 6   Alley            198 non-null    object 
 7   Lot Shape        2930 non-null   object 
 8   Land Contour     2930 non-null   object 
 9   Utilities        2930 non-null   object 
 10  Lot Config       2930 non-null   object 
 11  Land Slope       2930 non-null   object 
 12  Neighborhood     2930 non-null   object 
 13  Condition 1      2930 non-null   object 
 14  Condition 2      2930 non-null   object 
 15  Bldg Type        2930 non-null   object 
 16  House Style      2930 non-null   object 
 17  Overall Qual  